### PR TITLE
Initial iteration of resolutions

### PR DESCRIPTION
**Pull request by JayaKrishnaNamburu**
#13

### CODE REVIEW

**Comment by JayaKrishnaNamburu** [comment]
This generates a `import-map` of something like
```json
{
  "imports": {
    "package-b": "../package-b/index.js",
    "react": "./node_modules/react/index.js"
  },
  "scopes": {
    "./node_modules/react/": {
      "object-assign": "./node_modules/object-assign/index.js"
    }
  }
}
```

Should the `symlinks` be created and the mapping for `package-b` should go through like `./node_modules/package-b/index.js`.  At the moment, i don't think this map works as expected in pulling `package-b` from the repo.

**Comment by guybedford** [comment]
Great start! It should be possible to treat `resolutions` as consisting of `PackageTarget` strings, the same sort of thing we permit into the `install` function, see generator.install for how this is parsed. Then that can support version, registry, URL and relative path forms all within the standard target string parsing mechanisms.

When supporting resolutions to versioned packages, there is some circularity in place. Another place to handle these resolutions would be in installTarget - https://github.com/jspm/generator/blob/main/src/install/installer.ts#L243. That would avoid any interaction issues.

**Comment by guybedford** [comment]
> Should the symlinks be created and the mapping for package-b should go through like ./node_modules/package-b/index.js. At the moment, i don't think this map works as expected in pulling package-b from the repo.

Symlinks are handled separately in resolution now so there is no need to worry about them.

**Comment by JayaKrishnaNamburu** [comment]
> Then that can support version, registry, URL and relative path forms all within the standard target string parsing mechanisms.

If i understood correct, so a resolution can be defined as 

```js
const generator = new Generator({
  ...,
  resolutions: {
    "package-b": "../package-b",
    "package-c": {
         alias: "local-package",
         target: "./packages/local-pkg",
        subpath: "./feature"
     }
  },
});
```
Any resolution can accept a direct string, or just a object which can e parsed just as `install` method does.

**Comment by guybedford** [comment]
@JayaKrishnaNamburu there is no need to support an object form in resolutions, because all the properties of `Install` are also representable as strings, apart from alias. And alias just refers to the LHS string `"package-c"` in your example above. Therefore the types of Install objects necessary in resolutions are all representable as strings (ie the list of formats `./local`, `registry:name@version`, https://url.com/package`, `file:///absolute/package/path`, `pkgName`, `pkgName@version`).

The parsing functions for this may need a bit of checking though certainly.

**Comment by guybedford** [comment]
Note that resolutions is a package resolution, not an import map resolution, so doesn't refer to the final module URL, but rather effectively the package URL.

**Comment by JayaKrishnaNamburu** [comment]
Got it now, thank you 👍

**Comment by JayaKrishnaNamburu** [comment]
Hey, was little caught-up on things. Will be on this again this weekend 😅

**Comment by guybedford** [comment]
Thanks for the update @JayaKrishnaNamburu just let me know if I can assist further.

**Comment by guybedford** [comment]
This was finally landed in Implemented in https://github.com/jspm/generator/pull/75.

**Pull request closed without merging**
