### PR TITLE
Deno support

### PR DESCRIPTION
**Pull request by guybedford**
Deno support both for running this generator itself in Deno and for supporting Deno maps in general through the generator.

Pending @jspm/core update.

### CODE REVIEW

**Comment by vovacodes** [comment]
woot! Gonna test it later today

**Comment by guybedford** [comment]
CI is _finally_ passing on this. I'm still working on trying to get some more involved Deno npm package tests working, so will keep this open while I continue to work on that.

**Comment by fusionstrings** [comment]
> CI is _finally_ passing on this. I'm still working on trying to get some more involved Deno npm package tests working, so will keep this open while I continue to work on that.
I've been waiting for this. Thanks a lot. 🥇 💯 
Is it possible to try it out now?

**Comment by guybedford** [comment]
I can merge this PR as-is the main issue is that the core library needs to be published to npm. And I want to make sure I do some more comprehensive testing before doing that.

For that reason I'd suggest cloning this branch with submodules and running `npm run build` to test it out in the mean time. Hopefully I'll be able to get enough testing done to have some standard npm examples working in the next few days.

**Comment by guybedford** [comment]
Rebased - this is now failing on getting @babel/core to work via JSPM on Deno for the self-test. Which is a good self-test to get working.

**Comment by guybedford** [comment]
Finally landed. This will release along with the next @jspm/core update.

**Pull request merged**
